name: Check Rebar Dependencies

on: [pull_request]

jobs:
  check_deps_integrity:
    runs-on: ubuntu-20.04
    # FIXME: use tagged version once merged
    container: ghcr.io/emqx/emqx-builder/elixir:1.13.1-23.3.4.9-3-ubuntu20.04

    steps:
      - uses: actions/checkout@v2
      - name: Run check-deps-integrity.escript
        run: ./scripts/check-deps-integrity.escript
