name: Check emqx app standalone

on:
  push:
    tags:
      - v*
      - e*
  pull_request:

jobs:
  check_all:
    strategy:
      matrix:
        otp:
          - 23.3.4.9-3
          - 24.1.5-3
        # no need to use more than 1 version of Elixir, since tests
        # run using only Erlang code.  This is needed just to specify
        # the base image.
        elixir:
          - 1.13.1

    runs-on: ubuntu-20.04
    container: "ghcr.io/emqx/emqx-builder/5.0.0:${{ matrix.elixir}}-${{ matrix.otp }}-ubuntu20.04"

    steps:
    - uses: actions/checkout@v2
    - name: run
      run: |
        make ensure-rebar3
        cp rebar3 apps/emqx/
        cd apps/emqx
        ./rebar3 xref
        ./rebar3 dialyzer
        ./rebar3 eunit -v
        ./rebar3 ct -v
        ./rebar3 proper -d test/props
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: logs
        path: apps/emqx/_build/test/logs
